//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing;
using System.Globalization;
using System.Resources;

namespace Artemisapp_UX.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, images, and so on.
    /// </summary>
    internal static class Resources {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("Artemisapp_UX.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Generated properties for images/resources referenced in the .resx
        internal static Bitmap esquina {
            get {
                object obj = ResourceManager.GetObject("esquina", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap Fondo_patitas {
            get {
                object obj = ResourceManager.GetObject("Fondo patitas", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap Fondo_MenuStrip {
            get {
                object obj = ResourceManager.GetObject("Fondo MenuStrip", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap gato1 {
            get {
                object obj = ResourceManager.GetObject("gato1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap gato2 {
            get {
                object obj = ResourceManager.GetObject("gato2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap gatos4 {
            get {
                object obj = ResourceManager.GetObject("gatos4", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap bloque_imagen {
            get {
                object obj = ResourceManager.GetObject("bloque imagen", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap Login_Image {
            get {
                object obj = ResourceManager.GetObject("Login Image", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap _20231011_115130 {
            get {
                object obj = ResourceManager.GetObject("20231011_115130", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
